  # extractors
  filedigest:
    image: clowder/extractors-digest
    restart: always
    environment:
      RABBITMQ_URI: "amqp://rabbitmq:5672"
      REGISTRATION_ENDPOINTS: "http://clowder:9000/api/extractors?key=r1ek3rs"
    depends_on:
      - clowder
      - rabbitmq
  
  imagepreview:
    image: clowder/extractors-image-preview
    environment:
      RABBITMQ_URI: "amqp://rabbitmq:5672"
      REGISTRATION_ENDPOINTS: "http://clowder:9000/api/extractors"
    depends_on:
      - clowder
      - rabbitmq
  
  imagemetadata:
    image: clowder/extractors-image-metadata
    environment:
      RABBITMQ_URI: "amqp://rabbitmq:5672"
      REGISTRATION_ENDPOINTS: "http://clowder/extractors"
    depends_on:
      - clowder
      - rabbitmq
  
  imagegeotiff:
    image: clowder/extractors-image-geotiff
    environment:
      RABBITMQ_URI: "amqp://rabbitmq:5672"
      REGISTRATION_ENDPOINTS: "http://clowder/extractors"
    depends_on:
      - clowder
      - rabbitmq
  
  geoshp:
    image: clowder/extractors-geo-shp
    environment:
      RABBITMQ_URI: "amqp://rabbitmq:5672"
      REGISTRATION_ENDPOINTS: "http://clowder/extractors"
      GEOSERVER_URL: "http://geoserver:8080/web"
      GEOSERVER_USERNAME: "admin"
      GEOSERVER_PASSWORD: "geoserver"
      GEOSERVER_WORKSPACE: "clowder"
    depends_on:
      - clowder
      - rabbitmq
      - geoserver

  geotiff:
    image: clowder/extractors-geo-tiff
    environment:
      RABBITMQ_URI: "amqp://rabbitmq:5672"
      REGISTRATION_ENDPOINTS: "http://clowder/extractors"
      GEOSERVER_URL: "http://geoserver:8080/web"
      GEOSERVER_USERNAME: "admin"
      GEOSERVER_PASSWORD: "geoserver"
      GEOSERVER_WORKSPACE: "clowder"
    depends_on:
      - clowder
      - rabbitmq
      - geoserver
  
