# clowder server
version: '3'

services:

  # mongo database used to store metadata/data
  mongo:
    image: mongo:latest
    restart: always
    user: "0:1258"
    ports:
      - "27017:27017"
    volumes:
      - /mnt/skope/staging/mongo:/data/db
  
  # rabbitmq to connect to extractors
  rabbitmq:
    image: rabbitmq:management
    restart: always
    user: "0:1258"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /mnt/skope/staging/rabbitmq:/var/lib/rabbitmq
  
  # elasticsearch to allow indexing
  elasticsearch:
    image: elasticsearch:2
    restart: always
    user: "0:1258"
    command: elasticsearch -Des.cluster.name="clowder"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /mnt/skope:/projects/skope
  
  # geoserver to render tiles
  geoserver:
    build: geoserver
    restart: always
    user: "0:1258"
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xmx1536M -XX:MaxPermSize=756M -Duser.timezone=GMT -Dorg.geotools.shapefile.datetime=true"
      GEOSERVER_DATA_DIR: "/projects/skope/staging/geoserver"
    volumes:
      - /mnt/skope:/projects/skope
  
  clowder:
    image: clowder/clowder:develop
    restart: always
    user: "0:1258"
    environment:
      CLOWDER_ADMIN: "jefft@illinois.edu"
      TOOLMANAGER_URI: "http://192.168.99.100:8080"
      MONGO_URI: "mongodb://mongo:27017/clowder"
      RABBITMQ_URI: "amqp://rabbitmq:5672"
      SMTP_HOST: smtp.ncsa.illinois.edu
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - ./clowder/custom:/home/clowder/clowder/custom
      - /mnt/skope:/projects/skope
    ports:
      - "9000:9000"

  web:
    build: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - rabbitmq
      - elasticsearch
      - geoserver
      - clowder
  
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1454

