# clowder server
version: '3.2'

services:

  # elasticsearch to allow indexing
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    restart: always
    user: "0:1258"
    environment:
      - cluster.name=skope
      - bootstrap.memory_lock=true
      - path.data=/projects/skope/staging/esdata
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/skope:/projects/skope
  
  # geoserver to render tiles
  geoserver:
    build: geoserver
    restart: always
    user: "0:1258"
    environment:
      JAVA_OPTS: "-Xmx1536M -XX:MaxPermSize=756M -Duser.timezone=GMT -Dorg.geotools.shapefile.datetime=true"
      GEOSERVER_DATA_DIR: "/projects/skope/staging/geoserver"
    volumes:
      - /mnt/skope:/projects/skope
  
  web:
    build: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - elasticsearch
      - geoserver
  
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1454

